(ns rivalchess-text.model.board-bitboards)

(def BITBOARD_WP 0)
(def BITBOARD_WN 1)
(def BITBOARD_WB 2)
(def BITBOARD_WQ 3)
(def BITBOARD_WK 4)
(def BITBOARD_WR 5)
(def BITBOARD_BP 6)
(def BITBOARD_BN 7)
(def BITBOARD_BB 8)
(def BITBOARD_BQ 9)
(def BITBOARD_BK 10)
(def BITBOARD_BR 11)
(def BITBOARD_ALL 12)
(def BITBOARD_FRIENDLY 13)
(def BITBOARD_ENEMY 14)
(def BITBOARD_ENPASSANTSQUARE 15)
(def BITBOARD_NONE 16)
(def BITBOARD_COUNT 17)

(def whiteBitboardTypes [BITBOARD_WP, BITBOARD_WN, BITBOARD_WB, BITBOARD_WR, BITBOARD_WQ, BITBOARD_WK])
(def blackBitboardTypes [BITBOARD_BP, BITBOARD_BN, BITBOARD_BB, BITBOARD_BR, BITBOARD_BQ, BITBOARD_BK])
(def allBitboardTypes [BITBOARD_WP,BITBOARD_BP,BITBOARD_WN,BITBOARD_BN,BITBOARD_WB,BITBOARD_BB,
                       BITBOARD_WR,BITBOARD_BR,BITBOARD_WQ,BITBOARD_BQ,BITBOARD_WK,BITBOARD_BK])


